#!/bin/bash
#This Script generates C Modules
read -p "Enter the name of the Module Auther: " authername
echo "
Hello ${authername} 
Wellcome to the C Programming Language Module Generator
"
read -p "Enter the name of the Module: " modulename
read -p "Enter the Version of the Module: " versionnumber



echo "/******************************************************************************
* @file:    ${modulename}_interface.h
* @author:  Copyright (c) `date +%Y` ${authername}.
* @license: GNU GPL version 3 or later.
*	    This is free software: you are free to change and redistribute it.  
*	    There is NO WARRANTY, to the extent permitted by law.
* @version: V${versionnumber}   
* @date:    `date -R`
* @brief:   A description of the module’s purpose.
*******************************************************************************/
#ifndef _${modulename}_INTERFACE_H
#define _${modulename}_INTERFACE_H

/* ==================================================================== */
/* ======================= Public Data Types ========================== */
/* ==================================================================== */

/* Public datatypes go here */




/* ==================================================================== */
/* ======================== Public Macros ============================= */
/* ==================================================================== */

/* Public Macro Definitions go here */




/* ==================================================================== */
/* ==================== Public Functions Declaration ================== */
/* ==================================================================== */

/* Public Functions Declaration go here */

/**
 * @brief---------------------> 
 * @param---------------------> None
 * @parameter1----------------> () 
 * @parameter2----------------> () 
 * @parameter3----------------> () 
 * @return--------------------> None
 * @preconditions-------------> None
 * @postconditions------------> None
 * @synchronous/asynchronous--> Synchronous
 * @reentrant/non-reentrant---> Reentrant               
 */



#endif
" 1> ${modulename}_interface.h


echo "/******************************************************************************
* @file:    ${modulename}_config.h
* @author:  Copyright (c) `date +%Y` ${authername}.
* @license: GNU GPL version 3 or later.
*	    This is free software: you are free to change and redistribute it.  
*	    There is NO WARRANTY, to the extent permitted by law.
* @version: V${versionnumber}   
* @date:    `date -R`
* @brief:   A description of the module’s purpose.
*******************************************************************************/
#ifndef _${modulename}_CONFIG_H
#define _${modulename}_CONFIG_H

/* ==================================================================== */
/* =================== Configurations Selection ======================= */
/* ==================================================================== */

/* Configurations Selection go here */




#endif
" 1> ${modulename}_config.h


echo "/******************************************************************************
* @file:    ${modulename}_private.h
* @author:  Copyright (c) `date +%Y` ${authername}.
* @license: GNU GPL version 3 or later.
*	    This is free software: you are free to change and redistribute it.  
*	    There is NO WARRANTY, to the extent permitted by law.
* @version: V${versionnumber}   
* @date:    `date -R`
* @brief:   A description of the module’s purpose.
*******************************************************************************/
#ifndef _${modulename}_PRIVATE_H
#define _${modulename}_PRIVATE_H

/* ==================================================================== */
/* ====================== Private Data Types ========================== */
/* ==================================================================== */

/* Definition of private datatypes go here */




/* ==================================================================== */
/* =================== Private Variables and Macros =================== */
/* ==================================================================== */

/* private variables and Macros definitions go here */




/* ==================================================================== */
/* ==================== Private Functions Declaration ================= */
/* ==================================================================== */

/* Private Functions Prototypes go here */




#endif
" 1> ${modulename}_private.h





echo "/******************************************************************************
* @file:    ${modulename}_program.c
* @author:  Copyright (c) `date +%Y` ${authername}.
* @license: GNU GPL version 3 or later.
*	    This is free software: you are free to change and redistribute it.  
*	    There is NO WARRANTY, to the extent permitted by law.
* @version: V${versionnumber}   
* @date:    `date -R`
* @brief:   A description of the module’s purpose.
*******************************************************************************/

/* ==================================================================== */
/* ========================== Include Files =========================== */
/* ==================================================================== */

/* Inclusion of Standard Types and Bit Math header files goes here */

/* Inclusion of Module header files goes here */
#include \"${modulename}_interface.h\"
#include \"${modulename}_private.h\"
#include \"${modulename}_config.h\"

/* Inclusion of interface header files of the Other Modules goes here */




/* ==================================================================== */
/* ======================== Global Variables ========================== */
/* ==================================================================== */

/* Global variables definitions go here */




/* ==================================================================== */
/* ================= Public Functions Implementation ================== */
/* ==================================================================== */

/* Functions Implementation public functions go here */




/* ==================================================================== */
/* ================ Private Functions Implementation ================== */
/* ==================================================================== */

/* Function Implementation for private (static) functions go here */





" 1> ${modulename}_program.c
clear
echo "${modulename} module was successfully created...."
